### ISSUE TITLE
whn Login Show Up Eror Code

### ISSUE THREAD

**Issue by Ratraz** [LongAKolangle/discord-owo-selfbot#19]
Error: Failed to find real token (6 times) [Captcha]        at DiscordAuthWebsocket._findRealToken (/storage/emulated/0/Download/discord-owo-selfbot/node_modules/discord.js-selfbot-v13/src/util/RemoteAuth.js:429:9)              at DiscordAuthWebsocket._findRealToken (/storage/emulated/0/Download/discord-owo-selfbot/node_modules/discord.js-selfbot-v13/src/util/RemoteAuth.js:479:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)                               2023-06-30 13:25:23 [PROMISE.ERROR] Error: Failed to find real token (6 times) [Captcha]

**Comment by LongAKolangle** [comment]
check out #2
