### ISSUE TITLE
fix??

### ISSUE THREAD

**Issue by vxnlolz** [LongAKolangle/discord-owo-selfbot#28]
2023-11-16 19:44:24 [INFO] Checking Account...
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at Function.from (node:buffer:323:9)
    at DiscordAuthWebsocket._decryptPayload (C:\Users\Esen\Desktop\discord-owo-selfbot-main\node_modules\discord.js-selfbot-v13\src\util\RemoteAuth.js:335:28)
    at DiscordAuthWebsocket._findRealToken (C:\Users\Esen\Desktop\discord-owo-selfbot-main\node_modules\discord.js-selfbot-v13\src\util\RemoteAuth.js:473:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
2023-11-16 19:44:28 [PROMISE.ERROR] Unhandled Rejection Found!

**Comment by F-Cloud-cod** [comment]
Normally, if you log in from a client, it will ask for bot validation and cactcha will resolve it, but since this bot does not have such a mechanism, it gives an error. I ran it once and it gave such an error the 2nd time, I will wait and hope the problem is solved.

**Comment by LongAKolangle** [comment]
> Normally, if you log in from a client, it will ask for bot validation and cactcha will resolve it, but since this bot does not have such a mechanism, it gives an error. I ran it once and it gave such an error the 2nd time, I will wait and hope the problem is solved.

Check this one out: https://github.com/LongAKolangle/discord-owo-selfbot/discussions/15#discussioncomment-6834540

**Comment by F-Cloud-cod** [comment]
Token:          Unknown
[DiscordRemoteAuth] Please check your phone again to confirm login.
[DiscordRemoteAuth] Get token success.
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
at Function.from (node:buffer:323:9)
at DiscordAuthWebsocket._decryptPayload (/home/discord-owo-selfbot/node_modules/discord.js-selfbot-v13/src/util/RemoteAuth.js:335:28)
at DiscordAuthWebsocket._findRealToken (/home/discord-owo-selfbot/node_modules/discord.js-selfbot-v13/src/util/RemoteAuth.js:473:27)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
code: 'ERR_INVALID_ARG_TYPE'
}
2023-12-30 17:25:40 [PROMISE.ERROR] Unhandled Rejection Found!

**Comment by F-Cloud-cod** [comment]
okay, the problem was fixed when I logged in with the token, thank you, it was a really nice project.

**Comment by 9020areeb** [comment]
> okay, the problem was fixed when I logged in with the token, thank you, it was a really nice project.

How can you explain me?

**Comment by F-Cloud-cod** [comment]
In folder lib, open DataCollector.ts with notepad/text editor and find those lines
Then delete them If you log in with a token, no problem :)
![image](https://github.com/LongAKolangle/discord-owo-selfbot/assets/79140476/7510f821-147e-4655-b485-47dfa1a16652)

**Comment by DvivekD** [comment]
theres no such lines though

**Comment by Kayows12** [comment]
> In folder lib, open DataCollector.ts with notepad/text editor and find those lines Then delete them If you log in with a token, no problem :) ![image](https://private-user-images.githubusercontent.com/79140476/297756157-7510f821-147e-4655-b485-47dfa1a16652.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNDQ5MzIsIm5iZiI6MTcxNTI0NDYzMiwicGF0aCI6Ii83OTE0MDQ3Ni8yOTc3NTYxNTctNzUxMGY4MjEtMTQ3ZS00NjU1LWI0ODUtNDdkZmExYTE2NjUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDA4NTAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1ZGUyYmU2MGFhZjI4Njg3M2E0Mzk0MjEwNmNiMzRjMjAzMTgwYzljZjcwZTM2M2NhNGFjYzEwY2M1NjAxMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NqBu565kWGhBLGWVLNwxZbNUZd9FdIom8NqJRuSpnX4)

Can you write down the command steps?
