### ISSUE TITLE
Authentication problem

### ISSUE THREAD

**Issue by Colly001** [LongAKolangle/discord-owo-selfbot#8]
(node:6192) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Error: Failed to find real token (6 times) [Captcha]
    at DiscordAuthWebsocket._findRealToken (D:\Andrei\discord-owo-selfbot-main\node_modules\discord.js-selfbot-v13\src\util\RemoteAuth.js:429:9)
    at DiscordAuthWebsocket._findRealToken (D:\Andrei\discord-owo-selfbot-main\node_modules\discord.js-selfbot-v13\src\util\RemoteAuth.js:479:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by LongAKolangle** [comment]
Check out this one pls: https://github.com/LongAKolangle/discord-owo-selfbot/issues/2
